---
title: "fantasyfootball"
author: "Taro Katayama"
date: "2023-08-27"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
#install.packages("stringdist")
library(tidyverse)
library(stringdist)



rankings<-read.csv("Data/FantasyPros.csv", header = TRUE)
underdog<-read.csv("Data/Underdog.csv", skip = 1, header = TRUE)
espn<- read.csv("Data/espn.csv", header = FALSE)

colnames(espn)<- c("Player", "ADP.ESPN")

overall<-rankings%>%
  select(1:2, 9)%>%
  slice(1:200)

overall.underdog<- underdog%>%
  select(1, 4, 7)%>%
  slice(1:200)

ultimate<- inner_join(overall, overall.underdog)

ultimate2<- inner_join(ultimate, espn)

merged_df<- merge(overall, overall.underdog, by.x = "Player", by.y = "Player", all=TRUE)

ultimate<- merge(espn, merged_df, by.x = "Player", by.y = "Player", all=TRUE)

ultimate<- ultimate%>% arrange(Rank)


ultimate$Value1<- ultimate$ADP.ESPN-ultimate$Current.ADP

value_underdog<- ultimate[order(ultimate$Value, decreasing = TRUE), ][1:20, ]

value_underdog<- value_underdog%>%select(1,2,5,7)


ultimate$Value2<- ultimate$ADP.ESPN-ultimate$AVG

value_ovr<- ultimate[order(ultimate$Value2, decreasing = TRUE), ][1:20, ]

value_ovr<- value_ovr%>%select(1,2,4,9)

# Create a bar plot
ggplot(value_underdog, aes(x = Player, y = Value)) +
  geom_bar(stat = "identity") +
  labs(title = "Top Value Picks", x = "Player", y = "Value")+
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5))


ggplot(value_ovr, aes(x = Player, y = Value2)) +
  geom_bar(stat = "identity") +
  labs(title = "Top Value Picks", x = "Player", y = "Value")+
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5))
```




```{r setup, include=FALSE}
colnames(ultimate)<- c("Rank", "Player", "ADP", "ADP.Underdog", "Rank.Underdog")

colnames(ultimate2)<- c("Rank", "Player", "ADP", "ADP.Underdog", "Rank.Underdog", "ADP.ESPN")


ADP<- ultimate%>%
  select(2:4)%>%
  mutate(Difference= ADP-ADP.Underdog)

value<-ultimate2%>%
  select(2,3,4,6)%>%
  mutate(value.underdog=ADP.ESPN-ADP.Underdog)%>%
  mutate(value.Pro=ADP.ESPN-ADP)

write.csv(value, file = "Data/value.csv")

```
